service: catalog-service
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /v1/.*
  script: main.app

- url: /_tasks/?.*
  script: main.task_queue_app

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(storage)/.*
